#!/usr/bin/env python3
"""
Setup MCP Environment

Sets up environment variables needed for MCP servers to work properly.
"""

import os
from pathlib import Path

def setup_environment():
    """Setup environment variables for MCP servers."""
    print("🔧 Setting up MCP Environment")
    print("=" * 40)
    
    # Check if .env file exists
    env_file = Path(".env")
    
    env_vars = {}
    
    # Read existing .env file if it exists
    if env_file.exists():
        print(f"📋 Reading existing .env file...")
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    # Set default values for MCP servers
    defaults = {
        "SALESFORCE_MCP_ENABLED": "true",
        "GMAIL_MCP_ENABLED": "true",
        "BILL_COM_MCP_ENABLED": "true",
        # Salesforce credentials (will need to be filled in by user)
        "SALESFORCE_USERNAME": "",
        "SALESFORCE_PASSWORD": "",
        "SALESFORCE_SECURITY_TOKEN": "",
        "SALESFORCE_ORG_ALIAS": "DEFAULT_TARGET_ORG",
        # Bill.com credentials (will need to be filled in by user)
        "BILL_COM_USERNAME": "",
        "BILL_COM_PASSWORD": "",
        "BILL_COM_ORG_ID": "",
        "BILL_COM_DEV_KEY": "",
        "BILL_COM_ENVIRONMENT": "sandbox"
    }
    
    # Update with defaults (don't overwrite existing values)
    updated = False
    for key, default_value in defaults.items():
        if key not in env_vars:
            env_vars[key] = default_value
            updated = True
            print(f"✅ Added {key}={default_value}")
        else:
            print(f"📋 Keeping existing {key}={env_vars[key]}")
    
    # Write back to .env file
    if updated:
        print(f"\n💾 Writing updated .env file...")
        with open(env_file, 'w') as f:
            f.write("# MCP Server Environment Variables\n")
            f.write("# Generated by setup_mcp_environment.py\n\n")
            
            # Group by service
            f.write("# MCP Server Enablement\n")
            for key in ["SALESFORCE_MCP_ENABLED", "GMAIL_MCP_ENABLED", "BILL_COM_MCP_ENABLED"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            f.write("\n# Salesforce Configuration\n")
            for key in ["SALESFORCE_USERNAME", "SALESFORCE_PASSWORD", "SALESFORCE_SECURITY_TOKEN", "SALESFORCE_ORG_ALIAS"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            f.write("\n# Bill.com Configuration\n")
            for key in ["BILL_COM_USERNAME", "BILL_COM_PASSWORD", "BILL_COM_ORG_ID", "BILL_COM_DEV_KEY", "BILL_COM_ENVIRONMENT"]:
                if key in env_vars:
                    f.write(f"{key}={env_vars[key]}\n")
            
            # Add any other existing variables
            f.write("\n# Other Environment Variables\n")
            for key, value in env_vars.items():
                if key not in defaults:
                    f.write(f"{key}={value}\n")
        
        print(f"✅ Environment file updated!")
    else:
        print(f"📋 No updates needed - all variables already set")
    
    # Check for missing credentials
    print(f"\n🔍 Checking Credentials Status")
    print("-" * 30)
    
    missing_creds = []
    
    # Check Salesforce
    sf_creds = ["SALESFORCE_USERNAME", "SALESFORCE_PASSWORD", "SALESFORCE_SECURITY_TOKEN"]
    sf_missing = [key for key in sf_creds if not env_vars.get(key)]
    if sf_missing:
        print(f"⚠️  Salesforce: Missing {', '.join(sf_missing)}")
        missing_creds.extend(sf_missing)
    else:
        print(f"✅ Salesforce: All credentials configured")
    
    # Check Bill.com
    bc_creds = ["BILL_COM_USERNAME", "BILL_COM_PASSWORD", "BILL_COM_ORG_ID", "BILL_COM_DEV_KEY"]
    bc_missing = [key for key in bc_creds if not env_vars.get(key)]
    if bc_missing:
        print(f"⚠️  Bill.com: Missing {', '.join(bc_missing)}")
        missing_creds.extend(bc_missing)
    else:
        print(f"✅ Bill.com: All credentials configured")
    
    # Check Gmail
    gmail_config_dir = Path.home() / ".gmail-mcp"
    gmail_creds = gmail_config_dir / "credentials.json"
    if gmail_creds.exists():
        print(f"✅ Gmail: OAuth credentials configured")
    else:
        print(f"⚠️  Gmail: OAuth credentials not found at {gmail_creds}")
        print(f"   Run: python3 backend/setup_gmail_oauth.py")
    
    # Summary
    print(f"\n📊 Setup Summary")
    print("=" * 20)
    print(f"✅ MCP servers enabled: Gmail, Salesforce, Bill.com")
    print(f"📋 Environment file: {env_file.absolute()}")
    
    if missing_creds:
        print(f"⚠️  Missing credentials: {len(missing_creds)} variables need values")
        print(f"   Edit {env_file} to add your actual credentials")
    else:
        print(f"🎉 All credentials configured!")
    
    print(f"\n🚀 Next Steps:")
    print(f"1. Edit {env_file} to add your actual credentials")
    print(f"2. Start MCP servers: python3 backend/start_mcp_servers.py start")
    print(f"3. Test agents: python3 backend/test_gmail_agent_debug.py")

if __name__ == "__main__":
    setup_environment()